// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Helpful runtime warning during development if env vars are missing
  // (don't throw — allow server-side tooling to import the file safely)
  // eslint-disable-next-line no-console
  console.warn('[supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY is not set. Supabase client may not work.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Guard access to `localStorage` to avoid errors in non-browser environments
const storage = typeof window !== 'undefined' && typeof window.localStorage !== 'undefined' ? window.localStorage : undefined;

// If the env vars are missing, avoid calling `createClient` with empty strings (which throws)
// and instead export a lightweight proxy that throws a helpful error when used.
function createDisabledClient() {
  const err = new Error('[supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY is not set. Initialize these variables to use Supabase client.');
  const handler: ProxyHandler<any> = {
    get() {
      throw err;
    },
    apply() {
      throw err;
    },
    construct() {
      throw err;
    }
  };
  return new Proxy({}, handler) as unknown as ReturnType<typeof createClient<Database>>;
}

export const supabase = (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY)
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createDisabledClient();

// Debug helper: optional runtime logging for outgoing requests to Supabase endpoints.
// Enable by setting `localStorage.setItem('debug_supabase', '1')` in the browser, then reload.
// This wrapper only logs when the flag is set to avoid noisy logs in production.
try {
  if (typeof window !== 'undefined' && typeof window.fetch === 'function') {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const _w: any = window;
    const originalFetch = _w.fetch.bind(_w);
    _w.fetch = async (input: RequestInfo, init?: RequestInit) => {
      try {
        const url = typeof input === 'string' ? input : (input as Request).url;
        const enabled = typeof window.localStorage !== 'undefined' && window.localStorage.getItem('debug_supabase') === '1';
        if (enabled && typeof url === 'string' && url.includes('.supabase.co')) {
          // Mask key when printing
          const maskedKey = SUPABASE_PUBLISHABLE_KEY ? `${String(SUPABASE_PUBLISHABLE_KEY).slice(0, 6)}...` : 'not-set';
          // eslint-disable-next-line no-console
          console.groupCollapsed('[supabase-debug] outgoing request to Supabase');
          // eslint-disable-next-line no-console
          console.log('URL:', url);
          // eslint-disable-next-line no-console
          console.log('Masked publishable key:', maskedKey);
          // Print headers if available
          if (init?.headers) {
            // Normalized printing for Headers / object
            const h = init.headers instanceof Headers ? Object.fromEntries(init.headers.entries()) : init.headers;
            // eslint-disable-next-line no-console
            console.log('Request headers:', h);
            // eslint-disable-next-line no-console
            console.log('Authorization:', (h as any)?.Authorization || (h as any)?.authorization || null);
            // eslint-disable-next-line no-console
            console.log('apikey:', (h as any)?.apikey || null);
          }
          // eslint-disable-next-line no-console
          console.groupEnd();
        }
      } catch (e) {
        // swallow
      }
      return originalFetch(input, init);
    };
  }
} catch (err) {
  // ignore
}